config/routes.rb
AmesaVote::Application.routes.draw do
  devise_for :admins
  devise_for :voters

  root :to => "home#index"
  
  namespace :admin do
    resources :ballots
  end
  
  match 'vote/error' => 'vote#error', :as => :vote_error
  match '/vote/' => 'vote#index'
  get '/vote/:ballot_id' => 'vote#ballot'
  post '/vote/:ballot_id' => 'vote#submit_vote'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions
  has_and_belongs_to_many :voters
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :ballot
  has_many :question_choices
  accepts_nested_attributes_for :question_choices
end

app/models/question_choice.rb
class QuestionChoice < ActiveRecord::Base
  belongs_to :question
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, # :registerable, -- commented out so it's user console only.
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_and_belongs_to_many :ballots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  before_filter :authenticate_admin!
  # GET /ballots
  # GET /ballots.xml
  def index
    @ballots = Ballot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ballots }
    end
  end

  # GET /ballots/1
  # GET /ballots/1.xml
  def show
    @ballot = Ballot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ballot }
    end
  end

  # GET /ballots/new
  # GET /ballots/new.xml
  def new
    @ballot = Ballot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ballot }
    end
  end

  # GET /ballots/1/edit
  def edit
    @ballot = Ballot.find(params[:id])
  end

  # POST /ballots
  # POST /ballots.xml
  def create
    @ballot = Ballot.new(params[:ballot])

    respond_to do |format|
      if @ballot.save
        format.html { redirect_to(@ballot, :notice => 'Ballot was successfully created.') }
        format.xml  { render :xml => @ballot, :status => :created, :location => @ballot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ballot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ballots/1
  # PUT /ballots/1.xml
  def update
    @ballot = Ballot.find(params[:id])

    respond_to do |format|
      if @ballot.update_attributes(params[:ballot])
        format.html { redirect_to(@ballot, :notice => 'Ballot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ballot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ballots/1
  # DELETE /ballots/1.xml
  def destroy
    @ballot = Ballot.find(params[:id])
    @ballot.destroy

    respond_to do |format|
      format.html { redirect_to(ballots_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  before_filter :authenticate_voter!
  
  def ballot
    if user_voted?
      redirect_to :vote_error
      return
    else
      @ballot = Ballot.find_by_id params[:ballot_id]
    end
  end
  
  def index
    @ballots = Ballot.all
  end
  
  def submit_vote 
    if user_voted?
      redirect_to :vote_error
    else
      Ballot.transaction do 
        @ballot = Ballot.find_by_id params[:ballot_id]
        @ballot_votes = params[:ballot_form]
        @ballot_votes.each do |key,value|
          question = @ballot.questions.find_by_id(key)
          choice = question.question_choices.find_by_id(value, :lock => true)
          choice.increment!(:votes_for)
        end
        current_voter.ballots << @ballot
      end
    end
  end
  
  def error
  end
  
  private
  def user_voted?
    current_voter.ballots.include? Ballot.find_by_id(params[:ballot_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/ballots/_form.html.erb
<%= form_for([:admin, @ballot]) do |f| %>
  <% if @ballot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ballot.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @ballot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
	<div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballots/edit.html.erb
<h1>Editing Ballot</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @ballot] %> |
<%= link_to 'Back', admin_ballots_path %>

app/views/ballots/index.html.erb
<h1>Listing Ballots</h1>

<table>
  <tr>
    <th>Ballot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ballots.each do |ballot| %>
  <tr>
    <td><%= ballot.title %></td>
    <td><%= link_to 'Show', [:admin, ballot] %></td>
    <td><%= link_to 'Edit', edit_admin_ballot_path(ballot) %></td>
    <td><%= link_to 'Destroy', [:admin, ballot], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ballot', new_admin_ballot_path %>

app/views/ballots/new.html.erb
<h1>New Ballot</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_ballots_path %>

app/views/ballots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ballot:</b>
  <%= @ballot.title %>
</p>
<p>
  <b>Description:</b>
  <%= @ballot.description %>
</p>


<%= link_to 'Edit', edit_admin_ballot_path(@ballot) %> |
<%= link_to 'Back', admin_ballots_path %>

app/views/home/index.html.erb
<h1>AMESA Vote</h1>
<h2>Arts Media and Engineering Student Association Online Election System</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmesaVote</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ballot_id %><br />
    <%= f.text_field :ballot_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Ballot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.ballot_id %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ballot:</b>
  <%= @question.ballot_id %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/send_keys/key_notification.text.erb
This email is to notify you (<% @voter.email %>) that you have been registered to vote in the upcoming Arizona State University School of Arts Media and Engineering Student Association (AMESA) general elections. The electronic election software is available at http://foo.bar/election. You must be on the ASU local network on campus, or using the AnyConnect VPN (see: http://vpn.asu.edu) from off-campus, in order to access this site. Once you log in, use the following credentials to access the ballot:

Email: <% @voter.email %>

Please be aware that you can vote exactly once. Your vote will not be cast until you click "Submit" at the bottom of the form. Once you submit your ballot, you CANNOT change your choices, so please make sure you have selected the options you want to support.

The source code for this electronic voting web application is available for your inspection at http://github.com/alterscapes/elections. If you have any concerns about the software, please contact Ryan at ryan.spicer@asu.edu as soon as possible.

If you believe you received this message in error, please contact Ryan at ryan.spicer@asu.edu as soon as possible and request that you be removed from the list.

app/views/vote/ballot.html.erb
<h2>Ballot for <%= @ballot.title %></h2>
<%= form_for(:ballot_form, :method => :post, :url => "/vote/#{@ballot.id}") do |form|%>
	<ol>
	<%- @ballot.questions.each do |question| %>
		<li><%= question.text %>
			<ul>
			<%- question.question_choices.each do |choice| %>
				<li>
					<%= form.radio_button question.id, choice.id %>
					<%=form.label question.id, choice.text %>
				</li>
			<%- end %>
			</ul>
			</li>
	<%- end %>
</ol>
<%= form.submit "Cast my Vote" %>
<%- end %>

app/views/vote/error.html.erb
<p>We're sorry, but our records show that you've already voted in this election. You cannot, for obvious reasons, vote twice. If you have any questions, please contact Ryan at ryan(dot)spicer(at)asu(dot)edu.

app/views/vote/index.html.erb
<h2>List of Available Ballots</h2>
<ul>
<%- @ballots.each do |ballot|%>
	<li><a href="/vote/<%=ballot.id%>"><%= ballot.title %></a></li>
<%- end %>
</ul>

app/views/vote/submit_vote.html.erb
<p>Thank you for your vote. It has now been counted.</p>